Allow sending request with different methods during connection
rtfol/aiohttp-sse-client pull request #66
Opened 2021-02-22 08:25 UTC by paulefoe

I have a case where I need to send a POST request to connect, which I unable to do right now. This PR fixes it without breaking backward compatibility.

2021-02-23 15:32 UTC, paulefoe commented
Kindly asking for a review from @rtfol

2021-02-23 16:35 UTC, awarecan requested changes
Thanks for the contribution ❤️ 

Can you update the document for the new parameter, and write an unit test for it?

2021-02-23 16:35 UTC, awarecan commented on aiohttp_sse_client/client.py
> +                 http_method='GET',
Can we move this into `option` parameter and also update the doc in the method comment? Please use `method` as the key name

2021-02-24 06:22 UTC, paulefoe commented on tests/web_platform_tests/test_request.py
> +    assert source._response.method == 'POST'
I'm wondering if this is useful at all?

With regards to the tests in general, for me every test was skipped unless I added the `pytest.mark.asyncio` flag, did I miss something?

2021-02-24 06:23 UTC, paulefoe commented on tests/web_platform_tests/test_request.py
> +
I can revert this, pycharm did it automatiaclly

2021-02-24 06:24 UTC, paulefoe commented
Also, thank you very much for the quick review! Awesome library :sunglasses:

2021-02-24 08:06 UTC, awarecan requested changes

2021-02-24 08:06 UTC, awarecan commented on tests/web_platform_tests/test_request.py
> +@pytest.mark.asyncio
it should be unnecessary

2021-02-24 08:06 UTC, awarecan commented on tests/web_platform_tests/test_request.py
> +        WPT_SERVER + 'resources/cache-control.event_stream?pipe=sub',
this endpoint supports POST method
```suggestion
        WPT_SERVER + 'resources/message.py',
```

2021-02-24 08:06 UTC, awarecan commented on tests/web_platform_tests/test_request.py
> +    )
'resources/message.py' supports POST method, we don't need to mock it

2021-02-24 08:06 UTC, awarecan commented on tests/web_platform_tests/test_request.py
> +    assert source._response.method == 'POST'
```suggestion
    async for e in source:
        assert e.data == "data"
        break
    await source.close()

```

2021-02-24 08:06 UTC, awarecan commented on tests/web_platform_tests/test_request.py
> +    assert source._response.method == 'POST'
```
> py.test
```
Simply execute py.test works fine for me on my MacOS with python 3.7.1

2021-02-24 09:56 UTC, paulefoe commented on tests/web_platform_tests/test_request.py
> +    assert source._response.method == 'POST'
I'm not going to lie, this is doesn't work for me on Linux with python 3.9.

All the test suites are skipped for me

2021-02-24 10:09 UTC, paulefoe commented on tests/web_platform_tests/test_request.py
> +    assert source._response.method == 'POST'
Same for 3.7.10

2021-02-26 06:39 UTC, paulefoe commented
Thanks for taking care about tests! Anything else has to be done?

2021-02-27 09:49 UTC, awarecan approved these changes
Looks good now. Thanks for your contribution 🎉

2021-02-27 09:49 UTC, merged

2021-02-28 19:15 UTC, paulefoe commented
Thanks for quick release! Keep up the good work :slightly_smiling_face: